<a href="https://colab.research.google.com/github/gcgauravchauhan10/Python_Practice_Codes/blob/main/Practice%20with%20Pandas1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
pd.__version__

'2.2.2'

In [ ]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'from_dummies',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']

In [ ]:
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers.readers:

read_csv(filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', *, sep: 'str | None | lib.NoDefault' = <no_default>, delimiter: 'str | None | lib.NoDefault' = None, header: "int | Sequence[int] | None | Literal['infer']" = 'infer', names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>, index_col: 'IndexLabel | Literal[False] | None' = None, usecols: 'UsecolsArgType' = None, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters: 'Mapping[Hashable, Callable] | None' = None, true_values: 'list | None' = None, false_values: 'list | None' = None, skipinitialspace: 'bool' = False, skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None, skipfooter: 'int' = 0, nrows: 'int | None' = None, na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None, keep_default_na: 'bool' = True, na_filter: 'bool' = True, verbose: 'bool | lib.NoDefault' = <no_default>, skip_blank_lines: 'bool' = True, parse_dates: 'bool | Sequence[Hashable] | None' = None, infer_datetime_format: 'bool | lib.NoDefault' = <no_default>, keep_date_col: 'bool | lib.NoDefault' = <no_default>, date_parser: 'Callable | lib.NoDefault' = <no_default>, date_format: 'str | dict[Hashable, str] | None' = None, dayfirst: 'bool' = False, cache_dates: 'bool' = True, iterator: 'bool' = False, chunksize: 'int | None' = None, compression: 'CompressionOptions' = 'infer', thousands: 'str | None' = None, decimal: 'str' = '.', lineterminator: 'str | None' = None, quotechar: 'str' = '"', quoting: 'int' = 0, doublequote: 'bool' = True, escapechar: 'str | None' = None, comment: 'str | None' = None, encoding: 'str | None' = None, encoding_errors: 'str | None' = 'strict', dialect: 'str | csv.Dialect | None' = None, on_bad_lines: 'str' = 'error', delim_whitespace: 'bool | lib.NoDefault' = <no_default>, low_memory: 'bool' = True, memory_map: 'bool' = False, float_precision: "Literal['high', 'legacy'] | None" = None, storage_options: 'StorageOptions | None' = None, dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>) -> 'DataFrame | TextFileReader'
    Read a comma-separated values (csv) file into DataFrame.

    Also supports optionally iterating or breaking of the file
    into chunks.

    Additional help can be found in the online docs for
    `IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

    Parameters
    ----------
    filepath_or_buffer : str, path object or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
        expected. A local file could be: file://localhost/path/to/table.csv.

        If you want to pass in a path object, pandas accepts any ``os.PathLike``.

        By file-like object, we refer to objects with a ``read()`` method, such as
        a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
    sep : str, default ','
        Character or regex pattern to treat as the delimiter. If ``sep=None``, the
        C engine cannot automatically detect
        the separator, but the Python parsing engine can, meaning the latter will
        be used and automatically detect the separator from only the first valid
        row of the file by Python's builtin sniffer tool, ``csv.Sniffer``.
        In addition, separators longer than 1 character and different from
        ``'\s+'`` will be interpreted as regular expressions and will also force
        the use of the Python parsing engine. Note that regex delimiters are prone
        to ignoring quoted data. Regex example: ``'\r\t'``.
    delimiter : str, optional
        Alias for ``sep``.
    header : int, Sequence of int, 'infer' or None, default 'infer'
        Row number(s) containing column labels and marking the start of the
        data (zero-indexed). Default behavior is to infer the column names: if no ``names``
        are passed the behavior is identical to ``header=0`` and column
        names are inferred from the first line of the file, if column
        names are passed explicitly to ``names`` then the behavior is identical to
        ``header=None``. Explicitly pass ``header=0`` to be able to
        replace existing names. The header can be a list of integers that
        specify row locations for a :class:`~pandas.MultiIndex` on the columns
        e.g. ``[0, 1, 3]``. Intervening rows that are not specified will be
        skipped (e.g. 2 in this example is skipped). Note that this
        parameter ignores commented lines and empty lines if
        ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
        data rather than the first line of the file.
    names : Sequence of Hashable, optional
        Sequence of column labels to apply. If the file contains a header row,
        then you should explicitly pass ``header=0`` to override the column names.
        Duplicates in this list are not allowed.
    index_col : Hashable, Sequence of Hashable or False, optional
      Column(s) to use as row label(s), denoted either by column labels or column
      indices.  If a sequence of labels or indices is given, :class:`~pandas.MultiIndex`
      will be formed for the row labels.

      Note: ``index_col=False`` can be used to force pandas to *not* use the first
      column as the index, e.g., when you have a malformed file with delimiters at
      the end of each line.
    usecols : Sequence of Hashable or Callable, optional
        Subset of columns to select, denoted either by column labels or column indices.
        If list-like, all elements must either
        be positional (i.e. integer indices into the document columns) or strings
        that correspond to column names provided either by the user in ``names`` or
        inferred from the document header row(s). If ``names`` are given, the document
        header row(s) are not taken into account. For example, a valid list-like
        ``usecols`` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
        Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
        To instantiate a :class:`~pandas.DataFrame` from ``data`` with element order
        preserved use ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]``
        for columns in ``['foo', 'bar']`` order or
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
        for ``['bar', 'foo']`` order.

        If callable, the callable function will be evaluated against the column
        names, returning names where the callable function evaluates to ``True``. An
        example of a valid callable argument would be ``lambda x: x.upper() in
        ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
        parsing time and lower memory usage.
    dtype : dtype or dict of {Hashable : dtype}, optional
        Data type(s) to apply to either the whole dataset or individual columns.
        E.g., ``{'a': np.float64, 'b': np.int32, 'c': 'Int64'}``
        Use ``str`` or ``object`` together with suitable ``na_values`` settings
        to preserve and not interpret ``dtype``.
        If ``converters`` are specified, they will be applied INSTEAD
        of ``dtype`` conversion.

        .. versionadded:: 1.5.0

            Support for ``defaultdict`` was added. Specify a ``defaultdict`` as input where
            the default determines the ``dtype`` of the columns which are not explicitly
            listed.
    engine : {'c', 'python', 'pyarrow'}, optional
        Parser engine to use. The C and pyarrow engines are faster, while the python engine
        is currently more feature-complete. Multithreading is currently only supported by
        the pyarrow engine.

        .. versionadded:: 1.4.0

            The 'pyarrow' engine was added as an *experimental* engine, and some features
            are unsupported, or may not work correctly, with this engine.
    converters : dict of {Hashable : Callable}, optional
        Functions for converting values in specified columns. Keys can either
        be column labels or column indices.
    true_values : list, optional
        Values to consider as ``True`` in addition to case-insensitive variants of 'True'.
    false_values : list, optional
        Values to consider as ``False`` in addition to case-insensitive variants of 'False'.
    skipinitialspace : bool, default False
        Skip spaces after delimiter.
    skiprows : int, list of int or Callable, optional
        Line numbers to skip (0-indexed) or number of lines to skip (``int``)
        at the start of the file.

        If callable, the callable function will be evaluated against the row
        indices, returning ``True`` if the row should be skipped and ``False`` otherwise.
        An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
    skipfooter : int, default 0
        Number of lines at bottom of file to skip (Unsupported with ``engine='c'``).
    nrows : int, optional
        Number of rows of file to read. Useful for reading pieces of large files.
    na_values : Hashable, Iterable of Hashable or dict of {Hashable : Iterable}, optional
        Additional strings to recognize as ``NA``/``NaN``. If ``dict`` passed, specific
        per-column ``NA`` values.  By default the following values are interpreted as
        ``NaN``: " ", "#N/A", "#N/A N/A", "#NA", "-1.#IND", "-1.#QNAN", "-NaN", "-nan",
        "1.#IND", "1.#QNAN", "<NA>", "N/A", "NA", "NULL", "NaN", "None",
        "n/a", "nan", "null ".

    keep_default_na : bool, default True
        Whether or not to include the default ``NaN`` values when parsing the data.
        Depending on whether ``na_values`` is passed in, the behavior is as follows:

        * If ``keep_default_na`` is ``True``, and ``na_values`` are specified, ``na_values``
          is appended to the default ``NaN`` values used for parsing.
        * If ``keep_default_na`` is ``True``, and ``na_values`` are not specified, only
          the default ``NaN`` values are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are specified, only
          the ``NaN`` values specified ``na_values`` are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are not specified, no
          strings will be parsed as ``NaN``.

        Note that if ``na_filter`` is passed in as ``False``, the ``keep_default_na`` and
        ``na_values`` parameters will be ignored.
    na_filter : bool, default True
        Detect missing value markers (empty strings and the value of ``na_values``). In
        data without any ``NA`` values, passing ``na_filter=False`` can improve the
        performance of reading a large file.
    verbose : bool, default False
        Indicate number of ``NA`` values placed in non-numeric columns.

        .. deprecated:: 2.2.0
    skip_blank_lines : bool, default True
        If ``True``, skip over blank lines rather than interpreting as ``NaN`` values.
    parse_dates : bool, list of Hashable, list of lists or dict of {Hashable : list}, default False
        The behavior is as follows:

        * ``bool``. If ``True`` -> try parsing the index. Note: Automatically set to
          ``True`` if ``date_format`` or ``date_parser`` arguments have been passed.
        * ``list`` of ``int`` or names. e.g. If ``[1, 2, 3]`` -> try parsing columns 1, 2, 3
          each as a separate date column.
        * ``list`` of ``list``. e.g.  If ``[[1, 3]]`` -> combine columns 1 and 3 and parse
          as a single date column. Values are joined with a space before parsing.
        * ``dict``, e.g. ``{'foo' : [1, 3]}`` -> parse columns 1, 3 as date and call
          result 'foo'. Values are joined with a space before parsing.

        If a column or index cannot be represented as an array of ``datetime``,
        say because of an unparsable value or a mixture of timezones, the column
        or index will be returned unaltered as an ``object`` data type. For
        non-standard ``datetime`` parsing, use :func:`~pandas.to_datetime` after
        :func:`~pandas.read_csv`.

        Note: A fast-path exists for iso8601-formatted dates.
    infer_datetime_format : bool, default False
        If ``True`` and ``parse_dates`` is enabled, pandas will attempt to infer the
        format of the ``datetime`` strings in the columns, and if it can be inferred,
        switch to a faster method of parsing them. In some cases this can increase
        the parsing speed by 5-10x.

        .. deprecated:: 2.0.0
            A strict version of this argument is now the default, passing it has no effect.

    keep_date_col : bool, default False
        If ``True`` and ``parse_dates`` specifies combining multiple columns then
        keep the original columns.
    date_parser : Callable, optional
        Function to use for converting a sequence of string columns to an array of
        ``datetime`` instances. The default uses ``dateutil.parser.parser`` to do the
        conversion. pandas will try to call ``date_parser`` in three different ways,
        advancing to the next if an exception occurs: 1) Pass one or more arrays
        (as defined by ``parse_dates``) as arguments; 2) concatenate (row-wise) the
        string values from the columns defined by ``parse_dates`` into a single array
        and pass that; and 3) call ``date_parser`` once for each row using one or
        more strings (corresponding to the columns defined by ``parse_dates``) as
        arguments.

        .. deprecated:: 2.0.0
           Use ``date_format`` instead, or read in as ``object`` and then apply
           :func:`~pandas.to_datetime` as-needed.
    date_format : str or dict of column -> format, optional
        Format to use for parsing dates when used in conjunction with ``parse_dates``.
        The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
        `strftime documentation
        <https://docs.python.org/3/library/datetime.html
        #strftime-and-strptime-behavior>`_ for more information on choices, though
        note that :const:`"%f"` will parse all the way up to nanoseconds.
        You can also pass:

        - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
            time string (not necessarily in exactly the same format);
        - "mixed", to infer the format for each element individually. This is risky,
            and you should probably use it along with `dayfirst`.

        .. versionadded:: 2.0.0
    dayfirst : bool, default False
        DD/MM format dates, international and European format.
    cache_dates : bool, default True
        If ``True``, use a cache of unique, converted dates to apply the ``datetime``
        conversion. May produce significant speed-up when parsing duplicate
        date strings, especially ones with timezone offsets.

    iterator : bool, default False
        Return ``TextFileReader`` object for iteration or getting chunks with
        ``get_chunk()``.
    chunksize : int, optional
        Number of lines to read from the file per chunk. Passing a value will cause the
        function to return a ``TextFileReader`` object for iteration.
        See the `IO Tools docs
        <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
        for more information on ``iterator`` and ``chunksize``.

    compression : str or dict, default 'infer'
        For on-the-fly decompression of on-disk data. If 'infer' and 'filepath_or_buffer' is
        path-like, then detect compression from the following extensions: '.gz',
        '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
        (otherwise no compression).
        If using 'zip' or 'tar', the ZIP file must contain only one data file to be read in.
        Set to ``None`` for no decompression.
        Can also be a dict with key ``'method'`` set
        to one of {``'zip'``, ``'gzip'``, ``'bz2'``, ``'zstd'``, ``'xz'``, ``'tar'``} and
        other key-value pairs are forwarded to
        ``zipfile.ZipFile``, ``gzip.GzipFile``,
        ``bz2.BZ2File``, ``zstandard.ZstdDecompressor``, ``lzma.LZMAFile`` or
        ``tarfile.TarFile``, respectively.
        As an example, the following could be passed for Zstandard decompression using a
        custom compression dictionary:
        ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

        .. versionadded:: 1.5.0
            Added support for `.tar` files.

        .. versionchanged:: 1.4.0 Zstandard support.

    thousands : str (length 1), optional
        Character acting as the thousands separator in numerical values.
    decimal : str (length 1), default '.'
        Character to recognize as decimal point (e.g., use ',' for European data).
    lineterminator : str (length 1), optional
        Character used to denote a line break. Only valid with C parser.
    quotechar : str (length 1), optional
        Character used to denote the start and end of a quoted item. Quoted
        items can include the ``delimiter`` and it will be ignored.
    quoting : {0 or csv.QUOTE_MINIMAL, 1 or csv.QUOTE_ALL, 2 or csv.QUOTE_NONNUMERIC, 3 or csv.QUOTE_NONE}, default csv.QUOTE_MINIMAL
        Control field quoting behavior per ``csv.QUOTE_*`` constants. Default is
        ``csv.QUOTE_MINIMAL`` (i.e., 0) which implies that only fields containing special
        characters are quoted (e.g., characters defined in ``quotechar``, ``delimiter``,
        or ``lineterminator``.
    doublequote : bool, default True
       When ``quotechar`` is specified and ``quoting`` is not ``QUOTE_NONE``, indicate
       whether or not to interpret two consecutive ``quotechar`` elements INSIDE a
       field as a single ``quotechar`` element.
    escapechar : str (length 1), optional
        Character used to escape other characters.
    comment : str (length 1), optional
        Character indicating that the remainder of line should not be parsed.
        If found at the beginning
        of a line, the line will be ignored altogether. This parameter must be a
        single character. Like empty lines (as long as ``skip_blank_lines=True``),
        fully commented lines are ignored by the parameter ``header`` but not by
        ``skiprows``. For example, if ``comment='#'``, parsing
        ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in ``'a,b,c'`` being
        treated as the header.
    encoding : str, optional, default 'utf-8'
        Encoding to use for UTF when reading/writing (ex. ``'utf-8'``). `List of Python
        standard encodings
        <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

    encoding_errors : str, optional, default 'strict'
        How encoding errors are treated. `List of possible values
        <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

        .. versionadded:: 1.3.0

    dialect : str or csv.Dialect, optional
        If provided, this parameter will override values (default or not) for the
        following parameters: ``delimiter``, ``doublequote``, ``escapechar``,
        ``skipinitialspace``, ``quotechar``, and ``quoting``. If it is necessary to
        override values, a ``ParserWarning`` will be issued. See ``csv.Dialect``
        documentation for more details.
    on_bad_lines : {'error', 'warn', 'skip'} or Callable, default 'error'
        Specifies what to do upon encountering a bad line (a line with too many fields).
        Allowed values are :

        - ``'error'``, raise an Exception when a bad line is encountered.
        - ``'warn'``, raise a warning when a bad line is encountered and skip that line.
        - ``'skip'``, skip bad lines without raising or warning when they are encountered.

        .. versionadded:: 1.3.0

        .. versionadded:: 1.4.0


To get the exact method on right hand side use pd.read_csv

In [ ]:
pd.read_csv?

In [ ]:
pd.read_csv('https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv')

,"This is a list of medallists at the Summer Olympic Games (1896-2004) with details of the year of the olympics, city, sport, discipline, athlete name, gender, event and medal",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"DISCLAIMER: No guarantees, express or implied,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
...,...,...,...,...,...,...,...,...,...,...,...
27174,2004,Athens,Fencing,Fencing,"LOGOUNOVA, Tatiana",RUS,Women,épée team,W,Gold,1
27175,2004,Athens,Fencing,Fencing,"SIVKOVA, Anna",RUS,Women,épée team,W,Gold,1
27176,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver,2
27177,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver,2
27178,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver,2

Alternate method- Get file into the computer from github

In [ ]:
!wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

--2026-05-20 16:25:07--  https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/jonfernandes/pandas_essential/main/olympics_1896_2004.csv [following]
--2026-05-20 16:25:07--  https://raw.githubusercontent.com/jonfernandes/pandas_essential/main/olympics_1896_2004.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2398388 (2.3M) [text/plain]
Saving to: ‘olympics_1896_2004.csv’

olympics_1896_2004. 100%[===================>]   2.29M  --.-KB/s    in 0.07s

2026-05-20 16:25:07 (34.3 MB/s) - ‘olympics_1896_2004.csv’ saved [2398388/2398388]

This should then follow the below step

In [ ]:
from google.colab import files

In [ ]:
!ls -la

total 2360
drwxr-xr-x 1 root root    4096 May 20 16:25 .
drwxr-xr-x 1 root root    4096 May 20 16:19 ..
drwxr-xr-x 4 root root    4096 May 12 13:29 .config
-rw-r--r-- 1 root root 2398388 May 20 16:25 olympics_1896_2004.csv
drwxr-xr-x 1 root root    4096 May 12 13:29 sample_data

In [ ]:
pd.read_csv('olympics_1896_2004.csv')

,"This is a list of medallists at the Summer Olympic Games (1896-2004) with details of the year of the olympics, city, sport, discipline, athlete name, gender, event and medal",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"DISCLAIMER: No guarantees, express or implied,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
...,...,...,...,...,...,...,...,...,...,...,...
27174,2004,Athens,Fencing,Fencing,"LOGOUNOVA, Tatiana",RUS,Women,épée team,W,Gold,1
27175,2004,Athens,Fencing,Fencing,"SIVKOVA, Anna",RUS,Women,épée team,W,Gold,1
27176,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver,2
27177,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver,2
27178,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver,2

In [ ]:
pd.read_csv(filepath_or_buffer = 'olympics_1896_2004.csv')

,"This is a list of medallists at the Summer Olympic Games (1896-2004) with details of the year of the olympics, city, sport, discipline, athlete name, gender, event and medal",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"DISCLAIMER: No guarantees, express or implied,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
...,...,...,...,...,...,...,...,...,...,...,...
27174,2004,Athens,Fencing,Fencing,"LOGOUNOVA, Tatiana",RUS,Women,épée team,W,Gold,1
27175,2004,Athens,Fencing,Fencing,"SIVKOVA, Anna",RUS,Women,épée team,W,Gold,1
27176,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver,2
27177,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver,2
27178,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver,2

print in form of a dataframe

In [ ]:
oo = pd.read_csv('olympics_1896_2004.csv')

In [ ]:
oo = pd.read_csv('olympics_1896_2004.csv',skiprows = 5)

In [ ]:
filename = 'olympics_1896_2004.csv'

In [ ]:
print(oo)
oo.sample(3) #For taking random sample

       Year    City      Sport     Discipline        Athlete Name  NOC Gender  \
0      1896  Athens    Cycling  Cycling Track       FLAMENG, Léon  FRA    Men
1      1896  Athens    Cycling  Cycling Track  KOLETTIS, Georgios  GRE    Men
2      1896  Athens  Athletics      Athletics       LANE, Francis  USA    Men
3      1896  Athens  Athletics      Athletics    SZOKOLYI, Alajos  HUN    Men
4      1896  Athens  Athletics      Athletics       BURKE, Thomas  USA    Men
...     ...     ...        ...            ...                 ...  ...    ...
27169  2004  Athens    Fencing        Fencing  LOGOUNOVA, Tatiana  RUS  Women
27170  2004  Athens    Fencing        Fencing       SIVKOVA, Anna  RUS  Women
27171  2004  Athens    Fencing        Fencing      BOKEL, Claudia  GER  Women
27172  2004  Athens    Fencing        Fencing     DUPLITZER, Imke  GER  Women
27173  2004  Athens    Fencing        Fencing   HEIDEMANN, Britta  GER  Women

           Event Event Gender   Medal  Position
0          100km            M    Gold         1
1          100km            M  Silver         2
2           100m            M  Bronze         3
3           100m            M  Bronze         3
4           100m            M    Gold         1
...          ...          ...     ...       ...
27169  épée team            W    Gold         1
27170  épée team            W    Gold         1
27171  épée team            W  Silver         2
27172  épée team            W  Silver         2
27173  épée team            W  Silver         2

[27174 rows x 11 columns]

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
25506,2004,Athens,Athletics,Athletics,"PATTON, Darvis",USA,Men,4x100m relay,M,Silver,2
8130,1952,Helsinki,Aquatics,Swimming,"NOVAK-GERARD, Eva",HUN,Women,400m freestyle,W,Silver,2
20889,1992,Barcelona,Archery,Archery,"VALEEVA, Natalia",EUN,Women,individual (FITA Olympic round - 70m),W,Bronze,3

In [ ]:
pd.read_csv(filename,sep = ',',skiprows = 5) #sep ==> Separator / delimiter for files other than CSVs

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold,1
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver,2
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze,3
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze,3
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold,1
...,...,...,...,...,...,...,...,...,...,...,...
27169,2004,Athens,Fencing,Fencing,"LOGOUNOVA, Tatiana",RUS,Women,épée team,W,Gold,1
27170,2004,Athens,Fencing,Fencing,"SIVKOVA, Anna",RUS,Women,épée team,W,Gold,1
27171,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver,2
27172,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver,2
27173,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver,2

In [ ]:
type(oo)

pandas.core.frame.DataFrame

In [ ]:
oo['Discipline']  #case sensitive

0        Cycling Track
1        Cycling Track
2            Athletics
3            Athletics
4            Athletics
             ...
27169          Fencing
27170          Fencing
27171          Fencing
27172          Fencing
27173          Fencing
Name: Discipline, Length: 27174, dtype: object

In [ ]:
oo.Discipline

0        Cycling Track
1        Cycling Track
2            Athletics
3            Athletics
4            Athletics
             ...
27169          Fencing
27170          Fencing
27171          Fencing
27172          Fencing
27173          Fencing
Name: Discipline, Length: 27174, dtype: object

In [ ]:
oo.columns

Index(['Year', 'City', 'Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal', 'Position'],
      dtype='object')

In [ ]:
type(oo.Discipline)

pandas.core.series.Series

In [ ]:
oo.Discipline

0        Cycling Track
1        Cycling Track
2            Athletics
3            Athletics
4            Athletics
             ...
27169          Fencing
27170          Fencing
27171          Fencing
27172          Fencing
27173          Fencing
Name: Discipline, Length: 27174, dtype: object

In [ ]:
oo['Athlete Name']

0             FLAMENG, Léon
1        KOLETTIS, Georgios
2             LANE, Francis
3          SZOKOLYI, Alajos
4             BURKE, Thomas
                ...
27169    LOGOUNOVA, Tatiana
27170         SIVKOVA, Anna
27171        BOKEL, Claudia
27172       DUPLITZER, Imke
27173     HEIDEMANN, Britta
Name: Athlete Name, Length: 27174, dtype: object

In [ ]:
oo.Athlete Name #Dot notation will not work if there is a space in the series / attribute name

SyntaxError: invalid syntax (810197084.py, line 1)

In [ ]:
oo.Year.unique() #Provides unique years in an array

In [ ]:
type(oo.Year.unique())

In [ ]:
oo.Year.unique?

In [ ]:
oo.Sport.unique()

In [ ]:
oo.Sport.unique?

In [ ]:
oo.Year.value_counts() #To calculate the count of occurence of each of the Year value

In [ ]:
oo.Year.value_counts(normalize =True) #Normalize will give proportion (discribution) by year

Practice Question - What is the time range covered in this dataset?

In [ ]:
time_range = oo.Year.max() - oo.Year.min()
print(time_range," Years")

Practice Question - The Olympics take place every four years. why are there missing years?

In [ ]:
#Find out the missing years
unique_years = oo.Year.unique()
print(unique_years)

In [ ]:
i=1
missing_years=[]
for i in range(1,len(unique_years)-1):
  curr_year = unique_years[i]
  prev_year = unique_years[i-1]
  while prev_year + 4 < curr_year:
    prev_year +=4
    missing_years.append(int(prev_year))
i +=1
print(missing_years)

World war 1 and world war 2 were the reasons for missing olympic years

3. What are the types of medals awarded?
4. Across all of the Opympic Games, how many gold, silver and broze medals have there been?
5. Why are there not an equal number of gold, silver and broze medals?
6. There are more gold medals than silver and more silver medals than broze. Why might that be?
7. What are the different National Olympic Committees?
8. What does the NOC 'ZZX' represent?

In [ ]:
oo.sample(3)
medal_types = oo.Medal.unique()
print(medal_types)

In [ ]:
oo.Medal.value_counts()

In [ ]:
oo.sample(3)
oo.NOC.unique()

In [ ]:
#oo.query('NOC == "ZZX"') #Both are valid methods
oo[oo['NOC'] == "ZZX"]

#Pandas Lists and Dictionaries

In [ ]:
medals = ["Gold","Silver","Bronze"]
medals
type(medals)

In [ ]:
position = {"First" : "Gold",
            "Second" : "Silver",
            "Third" : "Bronze"}
position

In [ ]:
type(position)
position["First"] #Calling the dictionary for a meaning

Lists are used for storing series of items for example column names of a dataframe.
Disctionaries are using for mapping / looking up for meaning or definition or aliases

In [ ]:
oo.sample(3)
oo.rename?

In [ ]:
mapper = {"Athlete Name" : "Athlete_Name",
          "Event Gender" : "Event_Gender"}
oo.rename(columns=mapper) #Simply give the dict name and it will replace the aliases basis dict availability

In [ ]:
oo.sample(3) #This gives the same old values as the previous step only temporarity renamed but it was not saved in the dataframe

In [ ]:
oo = oo.rename(columns=mapper)
print(oo.head())

In [ ]:
oo.sample(3)

In [ ]:
oo_new = pd.read_csv('olympics_1896_2004.csv', skiprows = 5).rename(columns = mapper)
oo_new.sample(4)

In [ ]:
pd.read_csv?

In [ ]:
oo_nw1 = pd.read_csv('olympics_1896_2004.csv',skiprows = 5).rename(columns = {'Athlete Name' : 'Ath_Name','Event Gender' : 'Gender'})
oo_nw1.sample(3)

In [ ]:
oo_nw1.columns #to get the column names

In [ ]:
#to rename entire set of columns
column_names = ['Yr','City','Sport','Discipline','Athlete','No_obj_cert','Gender',
                'Event','Event_Gender','Medal','Position']
oo_nw1.columns = column_names
oo_nw1.sample(3)

In [ ]:
#now another way to do it all in one go - header=0 used to avoid column names appearing twice due to names usage
oo_nw2 = pd.read_csv('olympics_1896_2004.csv',skiprows = 5,names = column_names,header=0)
oo_nw2.sample(3)

Remove a Series (Column) or Row

In [ ]:
#Drop method (Remember - in pandas we refer to rows having axis of 0 and columns an axis of 1)
oo.drop('Position',axis = 1)

In [ ]:
oo.head()

In [ ]:
oo.drop('Position',axis = 0) #gives error as column has axis 1

In [ ]:
oo_nw3 = pd.read_csv('olympics_1896_2004.csv',skiprows = 5).rename(columns = {'Athlete Name' : 'Ath_Name','Event Gender' : 'Gender'}).drop('Position',axis = 1)
oo_nw3.head()

,Year,City,Sport,Discipline,Ath_Name,NOC,Gender,Event,Gender,Medal
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold

In [ ]:
oo_nw3 = pd.read_csv('olympics_1896_2004.csv',skiprows = 5).rename(columns = {'Athlete Name' : 'Ath_Name','Event Gender' : 'Gender'})
oo.drop('Position',axis = 1,inplace = True)
oo_nw3.head()

KeyError: "['Position'] not found in axis"

In [100]:
mapper = {'Athlete Name' : 'Ath_Name','Event Gender' : 'Gender'}

In [101]:
oo_nw3 = (pd.read_csv('olympics_1896_2004.csv',skiprows = 5)
          .rename(columns = mapper)
          .drop('Position',axis = 1)
          )
oo_nw3.head()

,Year,City,Sport,Discipline,Ath_Name,NOC,Gender,Event,Gender,Medal
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold

In [102]:
oo_nw3 = (pd.read_csv('olympics_1896_2004.csv',skiprows = 5)
          .rename(columns = mapper)
          .drop([0,1,2,3],axis = 0)
          )
oo_nw3.head()

,Year,City,Sport,Discipline,Ath_Name,NOC,Gender,Event,Gender,Medal,Position
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold,1
5,1896,Athens,Athletics,Athletics,"HOFMANN, Fritz",GER,Men,100m,M,Silver,2
6,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100m freestyle,M,Gold,1
7,1896,Athens,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100m freestyle,M,Silver,2
8,1896,Athens,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100m freestyle for sailors,M,Bronze,3

In [103]:
oo_nw3 = (pd.read_csv('olympics_1896_2004.csv',skiprows = 5)
          .rename(columns = mapper)
          .drop(['City','Sport'],axis = 1) #To delete multiple columns in one go. Inplace is not recommneded to use in chaining of methods
          )
oo_nw3.head()

,Year,Discipline,Ath_Name,NOC,Gender,Event,Gender,Medal,Position
0,1896,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold,1
1,1896,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver,2
2,1896,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze,3
3,1896,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze,3
4,1896,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold,1

No inplace available for below popular methods

In [104]:
pd.concat?

In [105]:
pd.merge?

In [106]:
oo_nw3.groupby?

filtering on a single condition

In [109]:
oo_nw3[oo_nw3.Year ==1896]

,Year,Discipline,Ath_Name,NOC,Gender,Event,Gender,Medal,Position
0,1896,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold,1
1,1896,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver,2
2,1896,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze,3
3,1896,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze,3
4,1896,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold,1
...,...,...,...,...,...,...,...,...,...
146,1896,Athletics,"CONNOLLY, James",USA,Men,triple jump,M,Gold,1
147,1896,Athletics,"TUFFERI, Alexandre",FRA,Men,triple jump,M,Silver,2
148,1896,Artistic G.,"WEINGÄRTNER, Hermann",GER,Men,vault,M,Bronze,3
149,1896,Artistic G.,"SCHUMANN, Carl",GER,Men,vault,M,Gold,1
150,1896,Artistic G.,"ZUTTER, Louis",SUI,Men,vault,M,Silver,2

In [110]:
oo_nw3[oo_nw3.Year <1896]

Empty DataFrame
Columns: [Year, Discipline, Ath_Name, NOC, Gender, Event, Gender, Medal, Position]
Index: []

In [112]:
oo_nw3[(oo_nw3.Year ==1896)|(oo_nw3.Year ==1912)] #| used for or condition

,Year,Discipline,Ath_Name,NOC,Gender,Event,Gender,Medal,Position
0,1896,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold,1
1,1896,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver,2
2,1896,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze,3
3,1896,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze,3
4,1896,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold,1
...,...,...,...,...,...,...,...,...,...
2817,1912,Fencing,"EVERITT, Arthur Francis G.",GBR,Men,épée team,M,Silver,2
2818,1912,Fencing,"HOLT, Martin Drummond",GBR,Men,épée team,M,Silver,2
2819,1912,Fencing,"MARTINEAU, Sydney",GBR,Men,épée team,M,Silver,2
2820,1912,Fencing,"MONTGOMERIE, Robert Cecil",GBR,Men,épée team,M,Silver,2
2821,1912,Fencing,"SELIGMAN, Edgar Isaac",GBR,Men,épée team,M,Silver,2

In [113]:
type(True)

bool

In [114]:
type(False)

bool

In [115]:
oo_nw3.Year.dtype

dtype('int64')

In [116]:
oo_nw3[(oo_nw3.Year ==1896) & (oo_nw3.Year ==1912)] # & used for and condition

Empty DataFrame
Columns: [Year, Discipline, Ath_Name, NOC, Gender, Event, Gender, Medal, Position]
Index: []

In [118]:
oo_nw3[(oo_nw3.Year ==1896) & (oo_nw3.NOC =='USA')] #& used for and condition

,Year,Discipline,Ath_Name,NOC,Gender,Event,Gender,Medal,Position
2,1896,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze,3
4,1896,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold,1
14,1896,Athletics,"CURTIS, Thomas",USA,Men,110m hurdles,M,Gold,1
23,1896,Athletics,"BLAKE, Arthur",USA,Men,1500m,M,Silver,2
28,1896,Shooting,"PAINE, John",USA,Men,25m army pistol,M,Gold,1
29,1896,Shooting,"PAINE, Sumner",USA,Men,25m army pistol,M,Silver,2
34,1896,Athletics,"BURKE, Thomas",USA,Men,400m,M,Gold,1
35,1896,Athletics,"JAMISON, Herbert",USA,Men,400m,M,Silver,2
40,1896,Shooting,"PAINE, Sumner",USA,Men,50m pistol (60 shots),M,Gold,1
55,1896,Athletics,"GARRETT, Robert",USA,Men,discus throw,M,Gold,1
74,1896,Athletics,"CLARK, Ellery",USA,Men,high jump,M,Gold,1
75,1896,Athletics,"CONNOLLY, James",USA,Men,high jump,M,Silver,2
76,1896,Athletics,"GARRETT, Robert",USA,Men,high jump,M,Silver,2
82,1896,Athletics,"CONNOLLY, James",USA,Men,long jump,M,Bronze,3
83,1896,Athletics,"CLARK, Ellery",USA,Men,long jump,M,Gold,1
84,1896,Athletics,"GARRETT, Robert",USA,Men,long jump,M,Silver,2
95,1896,Athletics,"HOYT, William Welles",USA,Men,pole vault,M,Gold,1
96,1896,Athletics,"TYLER, Albert",USA,Men,pole vault,M,Silver,2
109,1896,Athletics,"GARRETT, Robert",USA,Men,shot put,M,Gold,1
146,1896,Athletics,"CONNOLLY, James",USA,Men,triple jump,M,Gold,1

In [124]:
oo_nw3[(oo_nw3.Year ==1896) | (oo_nw3.Year ==1912)].Year.unique() #This is now a series / array

array([1896, 1912])